#!/usr/bin/env python
import sys
sys.path.insert(0, u'../../')
from netlib import certutils

if len(sys.argv) > 2:
    port = int(sys.argv[2])
else:
    port = 443

cert =  certutils.get_remote_cert(sys.argv[1], port, None)
print(u'CN:', cert.cn)
if cert.altnames:
    print(u'SANs:', end=u' ')
    for i in cert.altnames:
        print(u'\t', i)
